### Fetch all tasks

GET http://localhost:3200/tasks
Content-Type: application/json

### Create a new task
POST http://localhost:3200/tasks
Content-Type: application/json
{
    "title": "Mololor sit amet",
    "date": "2021-01-01T12:00:00Z",
    "description": "Lorem ipsum dolor sit amet",
    "priority": "normal",
    "status": "todo"
}

### Update a task
PUT http://localhost:3200/tasks
Content-Type: application/json
{
    "id": "f5703fbc-1e4c-4d03-8037-4a080e7a0912",
    "status": "inProgress"
}
